title: SimonNouwens
author:
  name: Simon Nouwens                      # Default author name
  email: 'simon@simonnouwens.nl'                   # Default author email
  copyright: "Copyright 2015 Simon Nouwens."
contact:
  address:
    - line: "Simon Nouwens"
    - line: "Breda, Nederland"
social:
  - url: 'https://twitter.com/simonnouwens'
    icon: 'twitter'
  - url: 'https://www.facebook.com/simon.nouwens'
    icon: 'facebook'
  - url: 'https://github.com/esquire900'
    icon: 'github'
othermenu:
  - text: "About"
    url: "about"
  - text: "Contact"
    url: "contact"
quicklinks:
  - text: "Portfolio"
    url: "portfolio"
  - text: "About"
    url: "about"
  - text: "Contact Us"
    url: "contact"          
taxonomies: [category,tag]                  # Arbitrary list of taxonomy types
metadata:
    description: 'Software Freelances and Human Technology Interaction Student'             # Site description
header_options:
  arrows: 'false'                            # Create Next and previous button
  autoslide: 'false'                        # Auto slideshow mode
  autoslideHoverStop: 'false'               # Pause auto slideshow mode on mouseover
  interval: '2000'                          # The interval between each slide (Interval in millisecond)
  loop: 'false'                             # Infinite slideshow             
  transition : zoom                         # Set the animation kind (fade/slide/page/zoom)
  itemsForSlide: '0'                        # Wrap each 'n' item
  touch: 'true'                             # Set a native slide for touch device
  swipe : 'true'                            # Enable swipe for touch device

footer:
    description: "Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Curabitur blandit tempus porttitor. Cras justo odio, dapibus ac facilisis in, egestas eget quam."
    contact_title: "Contact Info"
    links_title: "Quick Links"
    copyright_text: "Copyright 2013 Deliver. All Rights Reserved."
    feedburner: ""   # Your feedburner id for Newsletter footer modul


